version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rag_db
    restart: always
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.9.2
    container_name: rag_qdrant
    restart: always
    ports:
      - "6333:6333" # Port cho REST API và Web UI
      - "6334:6334" # Port cho gRPC
    volumes:
      - qdrant_data:/qdrant/storage
      
  adminer:
    image: adminer
    container_name: rag_adminer
    restart: always
    ports:
      - "8080:8080" # Ánh xạ port 8080 của host ra port 8080 của container

volumes:
  postgres_data:
  qdrant_data: